//USERS
export const GET_USER = 'GET_USER'

//CONTACTS
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS'

//REGIONS
export const GET_ALL_REGIONS = 'GET_ALL_REGIONS'
export const POST_REGIONS = 'POST_REGIONS'
export const DELETE_REGIONS = 'DELETE_REGIONS'

//COUNTRIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const POST_COUNTRIES = 'POST_COUNTRIES'
export const DELETE_COUNTRIES = 'DELETE_COUNTRIES'

//CITIES
export const GET_ALL_CITIES = 'GET_ALL_CITIES'

//COMPANY
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'
export const POST_COMPANIES = 'POST_COMPANIES'
export const DELETE_COMPANIES = 'DELETE_COMPANIES'


//COMMIMENT
export const GET_ALL_COMMITMENTS = 'GET_ALL_COMMITMENTS'


//PREFERENCE
export const GET_ALL_PREFERENCE = 'GET_ALL_PREFERENCE'


//CHANNEL
export const GET_ALL_CHANNELS = 'GET_ALL_CHANNELS'