//USERS
export const GET_USER = 'GET_USER'

//CONTACTS
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS'

//REGIONS
export const GET_ALL_REGIONS = 'GET_ALL_REGIONS'

//COUNTRIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'

//CITIES
export const GET_ALL_CITIES = 'GET_ALL_CITIES'

//COMPANY
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'
