//USERS
export const GET_USER = 'GET_USER'
export const UPDATE_USER = 'UPDATE_USER'

//CONTACTS
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS'
export const POST_CONTACTS = 'POST_CONTACTS'
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS'
export const DELETE_CONTACTS = 'DELETE_CONTACTS'

//REGIONS
export const GET_ALL_REGIONS = 'GET_ALL_REGIONS'
export const POST_REGION = 'POST_REGION'
export const UPDATE_REGION = 'UPDATE_REGION'
export const DELETE_REGION = 'DELETE_REGION'

//COUNTRIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const POST_COUNTRY = 'POST_COUNTRY'
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const DELETE_COUNTRY = 'DELETE_COUNTRY'


//CITIES
export const GET_ALL_CITIES = 'GET_ALL_CITIES'
export const POST_CITY = 'POST_CITY'
export const UPDATE_CITY = 'UPDATE_CITY'
export const DELETE_CITY = 'DELETE_CITY'

//COMPANY
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'
export const POST_COMPANY = 'POST_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'